query GetRevitTypes($streamId: String!, $objectId: String!) {
  stream(id: $streamId) {
    object(id: $objectId) {
      children(
        query: [
          {
            field: "speckle_type"
            value: "Objects.BuiltElements.Revit.RevitElementType:Objects.BuiltElements.Revit.RevitSymbolElementType"
            operator: "="
          }
        ]
      ) {
        totalCount
        objects {
          id
          speckleType
          data
        }
      }
    }
  }
}
